spring:
  datasource:
    url: jdbc:mysql://localhost:3306/social_network
    username: root
    password: db_114514
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8088
  servlet:
    session:
      timeout: 90s


mybatis-plus:
  mapperLocations: classpath:/xml/*.xml



